### ISSUE TITLE
Correct labels through bag-of-concepts

### ISSUE THREAD

**Issue by kkalouli** [kkalouli/SICK-processing#11]
Can we apply the bag-of-concepts approach on the whole SICK and found out if there are same "bags" with different labels? If so, we can correct these labels as same "bags" are expected to have same labels. Have to check.

**Comment by kkalouli** [comment]
Just checked: we cannot really do it because there is no pairs whose "bag of concepts" is exactly the same with the "bag" of another pair (at least not additionally to the one-word-apart pairs, which we already have). Closing "issue".

**Comment by vcvpaiva** [comment]
hmm, I thought the idea was to check that the two sentences in the pair had either the same bag of concepts or one concept difference? this is the idea of generalizing one-word-apart to one-concept-apart?

**Comment by kkalouli** [comment]
no, not quite. This idea is the one I had after coming back from the Prague workshop. There I heard about this idea of correcting annotated data: look for any two pieces of data that are the "same" but are annotated differently. This was presented in the context of POS tags so my idea how we could do the same for our case was to convert all pairs to bag of concepts and see if any two pairs have the same bags of concepts but different inference labels. Then, we could correct them. But as I wrote before, this is not the case: there are no two pairs with exactly the same bag of concepts, so this approach does not work in our case.
