### ISSUE TITLE
Using the Turku interface to check stats?

### ISSUE THREAD

**Issue by vcvpaiva** [kkalouli/SICK-processing#8]
The Turku guys have a great interface to inspect UD parse files, described in 
http://www.ep.liu.se/ecp/131/033/ecp17131033.pdf
Can we have our processed version of SICK using that interface?
it would help very much to check all compound nouns or all appositives, etc.

**Comment by kkalouli** [comment]
The web interface of the Turku system which is easy to use can only deal with the predefined treebanks that have been parsed by the guys themselves. You can apply the system to your own conllu of course but this would mean local installation of the system or putting up the webserver interface. Both would need some time ton install and would eventually require some shell commands to actually query stuff, so I am not sure if want to proceed in that.

**Comment by vcvpaiva** [comment]
closing this as we're not proceeding, for the time being.
